### ISSUE TITLE
For info

### ISSUE THREAD

**Issue by pombredanne** [opengamelicense/opengamelicense.org#1]
This is in ScanCode and its licensedb
https://scancode-licensedb.aboutcode.org/ogl-1.0a.html
since https://github.com/nexB/scancode-toolkit/commit/2e69d3401c61bfde425849bf74abef1aab012bd6#diff-53be08c7b90d5e7a9a2003ddd6039db781bd7af2b22e0c2b2ef9b8c415943155

**Comment by anthonyronda** [comment]
I appreciate the notice, thanks
